version: '3.8'

services:
  water-failure:
    image: 'water-failure'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: check-water-failure
    env_file: .env
    restart: 'always'
    networks:
      - 'sobek.io'

networks:
  sobek.io:
    external: true
